# Generated by Django 4.2.7 on 2024-01-15 11:00

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial_customers'),
        ('requests', '0002_initial_requests'),
        ('notifications', '0003_initial_notifications'),
        ('otp', '0004_initial_otp'),
        ('analytics', '0005_initial_analytics'),
    ]

    operations = [
        # Customer table indexes
        migrations.RunSQL(
            "CREATE INDEX idx_customer_firebase_uid ON customer(firebase_uid)",
            reverse_sql="DROP INDEX idx_customer_firebase_uid"
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_customer_email_active ON customer(email, is_active)",
            reverse_sql="DROP INDEX idx_customer_email_active"
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_customer_phone_active ON customer(phone, is_active)",
            reverse_sql="DROP INDEX idx_customer_phone_active"
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_customer_created_date ON customer(created_at)",
            reverse_sql="DROP INDEX idx_customer_created_date"
        ),
        
        # CardDetail table indexes
        migrations.RunSQL(
            "CREATE INDEX idx_carddetail_customer_active ON carddetail(customer_id, is_active)",
            reverse_sql="DROP INDEX idx_carddetail_customer_active"
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_carddetail_type_active ON carddetail(card_type, is_active)",
            reverse_sql="DROP INDEX idx_carddetail_type_active"
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_carddetail_limit ON carddetail(current_limit)",
            reverse_sql="DROP INDEX idx_carddetail_limit"
        ),
        
        # LimitRequest table indexes
        migrations.RunSQL(
            "CREATE INDEX idx_limitrequest_customer_status ON limitrequest(customer_id, status)",
            reverse_sql="DROP INDEX idx_limitrequest_customer_status"
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_limitrequest_reference ON limitrequest(reference_number)",
            reverse_sql="DROP INDEX idx_limitrequest_reference"
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_limitrequest_created_status ON limitrequest(created_at, status)",
            reverse_sql="DROP INDEX idx_limitrequest_created_status"
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_limitrequest_priority ON limitrequest(priority, status)",
            reverse_sql="DROP INDEX idx_limitrequest_priority"
        ),
        
        # NotificationLog table indexes
        migrations.RunSQL(
            "CREATE INDEX idx_notificationlog_customer_type ON notificationlog(customer_id, notification_type)",
            reverse_sql="DROP INDEX idx_notificationlog_customer_type"
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_notificationlog_status_created ON notificationlog(status, created_at)",
            reverse_sql="DROP INDEX idx_notificationlog_status_created"
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_notificationlog_category ON notificationlog(category, created_at)",
            reverse_sql="DROP INDEX idx_notificationlog_category"
        ),
        
        # OTPLog table indexes
        migrations.RunSQL(
            "CREATE INDEX idx_otplog_phone_status ON otplog(phone_number, status)",
            reverse_sql="DROP INDEX idx_otplog_phone_status"
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_otplog_created_type ON otplog(generated_at, otp_type)",
            reverse_sql="DROP INDEX idx_otplog_created_type"
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_otplog_expires_status ON otplog(expires_at, status)",
            reverse_sql="DROP INDEX idx_otplog_expires_status"
        ),
        
        # Analytics table indexes
        migrations.RunSQL(
            "CREATE INDEX idx_analytics_metric_name_time ON analyticsmetric(metric_name, timestamp)",
            reverse_sql="DROP INDEX idx_analytics_metric_name_time"
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_business_metrics_date ON businessmetrics(metric_date)",
            reverse_sql="DROP INDEX idx_business_metrics_date"
        ),
        
        # Composite indexes for common queries
        migrations.RunSQL(
            "CREATE INDEX idx_customer_search ON customer(firebase_uid, email, is_active)",
            reverse_sql="DROP INDEX idx_customer_search"
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_request_processing ON limitrequest(status, priority, created_at)",
            reverse_sql="DROP INDEX idx_request_processing"
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_notification_delivery ON notificationlog(customer_id, status, notification_type)",
            reverse_sql="DROP INDEX idx_notification_delivery"
        ),
        
        # Performance indexes for date range queries
        migrations.RunSQL(
            "CREATE INDEX idx_customer_date_range ON customer(created_at, is_active)",
            reverse_sql="DROP INDEX idx_customer_date_range"
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_request_date_range ON limitrequest(created_at, status, customer_id)",
            reverse_sql="DROP INDEX idx_request_date_range"
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_notification_date_range ON notificationlog(created_at, customer_id, status)",
            reverse_sql="DROP INDEX idx_notification_date_range"
        ),
        
        # Security and audit indexes
        migrations.RunSQL(
            "CREATE INDEX idx_otp_audit_security ON otpauditlog(ip_address, timestamp, action)",
            reverse_sql="DROP INDEX idx_otp_audit_security"
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_rate_limit_security ON otpratelimit(identifier, is_blocked, window_end)",
            reverse_sql="DROP INDEX idx_rate_limit_security"
        ),
    ]