# Generated by Django 4.2.7 on 2024-01-15 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_oracle_indexes'),
    ]

    operations = [
        # Add check constraints for data validation
        migrations.RunSQL(
            "ALTER TABLE customer ADD CONSTRAINT chk_customer_email_format CHECK (email LIKE '%@%')",
            reverse_sql="ALTER TABLE customer DROP CONSTRAINT chk_customer_email_format"
        ),
        migrations.RunSQL(
            "ALTER TABLE customer ADD CONSTRAINT chk_customer_phone_format CHECK (LENGTH(phone) >= 10)",
            reverse_sql="ALTER TABLE customer DROP CONSTRAINT chk_customer_phone_format"
        ),
        migrations.RunSQL(
            "ALTER TABLE customer ADD CONSTRAINT chk_customer_age CHECK (date_of_birth < SYSDATE - INTERVAL '18' YEAR)",
            reverse_sql="ALTER TABLE customer DROP CONSTRAINT chk_customer_age"
        ),
        
        # CardDetail constraints
        migrations.RunSQL(
            "ALTER TABLE carddetail ADD CONSTRAINT chk_card_limit_positive CHECK (current_limit >= 0)",
            reverse_sql="ALTER TABLE carddetail DROP CONSTRAINT chk_card_limit_positive"
        ),
        migrations.RunSQL(
            "ALTER TABLE carddetail ADD CONSTRAINT chk_card_expiry_month CHECK (expiry_month BETWEEN 1 AND 12)",
            reverse_sql="ALTER TABLE carddetail DROP CONSTRAINT chk_card_expiry_month"
        ),
        migrations.RunSQL(
            "ALTER TABLE carddetail ADD CONSTRAINT chk_card_expiry_year CHECK (expiry_year >= EXTRACT(YEAR FROM SYSDATE))",
            reverse_sql="ALTER TABLE carddetail DROP CONSTRAINT chk_card_expiry_year"
        ),
        
        # LimitRequest constraints
        migrations.RunSQL(
            "ALTER TABLE limitrequest ADD CONSTRAINT chk_request_limits CHECK (requested_limit > current_limit)",
            reverse_sql="ALTER TABLE limitrequest DROP CONSTRAINT chk_request_limits"
        ),
        migrations.RunSQL(
            "ALTER TABLE limitrequest ADD CONSTRAINT chk_request_positive_limits CHECK (current_limit >= 0 AND requested_limit > 0)",
            reverse_sql="ALTER TABLE limitrequest DROP CONSTRAINT chk_request_positive_limits"
        ),
        migrations.RunSQL(
            "ALTER TABLE limitrequest ADD CONSTRAINT chk_request_risk_score CHECK (risk_score IS NULL OR (risk_score >= 0 AND risk_score <= 100))",
            reverse_sql="ALTER TABLE limitrequest DROP CONSTRAINT chk_request_risk_score"
        ),
        
        # OTPLog constraints
        migrations.RunSQL(
            "ALTER TABLE otplog ADD CONSTRAINT chk_otp_expiry CHECK (expires_at > generated_at)",
            reverse_sql="ALTER TABLE otplog DROP CONSTRAINT chk_otp_expiry"
        ),
        migrations.RunSQL(
            "ALTER TABLE otplog ADD CONSTRAINT chk_otp_attempts CHECK (attempt_count >= 0 AND attempt_count <= max_attempts)",
            reverse_sql="ALTER TABLE otplog DROP CONSTRAINT chk_otp_attempts"
        ),
        migrations.RunSQL(
            "ALTER TABLE otplog ADD CONSTRAINT chk_otp_max_attempts CHECK (max_attempts > 0 AND max_attempts <= 10)",
            reverse_sql="ALTER TABLE otplog DROP CONSTRAINT chk_otp_max_attempts"
        ),
        
        # NotificationLog constraints
        migrations.RunSQL(
            "ALTER TABLE notificationlog ADD CONSTRAINT chk_notification_delivery_attempts CHECK (delivery_attempts >= 0 AND delivery_attempts <= 10)",
            reverse_sql="ALTER TABLE notificationlog DROP CONSTRAINT chk_notification_delivery_attempts"
        ),
        migrations.RunSQL(
            "ALTER TABLE notificationlog ADD CONSTRAINT chk_notification_title_length CHECK (LENGTH(title) >= 1)",
            reverse_sql="ALTER TABLE notificationlog DROP CONSTRAINT chk_notification_title_length"
        ),
        
        # Analytics constraints
        migrations.RunSQL(
            "ALTER TABLE customeranalytics ADD CONSTRAINT chk_analytics_request_counts CHECK (total_requests = approved_requests + rejected_requests)",
            reverse_sql="ALTER TABLE customeranalytics DROP CONSTRAINT chk_analytics_request_counts"
        ),
        migrations.RunSQL(
            "ALTER TABLE customeranalytics ADD CONSTRAINT chk_analytics_risk_score CHECK (risk_score IS NULL OR (risk_score >= 0 AND risk_score <= 100))",
            reverse_sql="ALTER TABLE customeranalytics DROP CONSTRAINT chk_analytics_risk_score"
        ),
        migrations.RunSQL(
            "ALTER TABLE customeranalytics ADD CONSTRAINT chk_analytics_satisfaction CHECK (satisfaction_score IS NULL OR (satisfaction_score >= 1 AND satisfaction_score <= 5))",
            reverse_sql="ALTER TABLE customeranalytics DROP CONSTRAINT chk_analytics_satisfaction"
        ),
        
        # System health constraints
        migrations.RunSQL(
            "ALTER TABLE systemhealthmetrics ADD CONSTRAINT chk_health_percentages CHECK (memory_usage_percent >= 0 AND memory_usage_percent <= 100 AND cpu_usage_percent >= 0 AND cpu_usage_percent <= 100 AND disk_usage_percent >= 0 AND disk_usage_percent <= 100)",
            reverse_sql="ALTER TABLE systemhealthmetrics DROP CONSTRAINT chk_health_percentages"
        ),
        migrations.RunSQL(
            "ALTER TABLE systemhealthmetrics ADD CONSTRAINT chk_health_response_times CHECK (api_response_time_ms >= 0 AND database_response_time_ms >= 0)",
            reverse_sql="ALTER TABLE systemhealthmetrics DROP CONSTRAINT chk_health_response_times"
        ),
        
        # Business metrics constraints
        migrations.RunSQL(
            "ALTER TABLE businessmetrics ADD CONSTRAINT chk_business_counts CHECK (total_customers >= 0 AND new_customers >= 0 AND active_customers >= 0 AND total_requests >= 0)",
            reverse_sql="ALTER TABLE businessmetrics DROP CONSTRAINT chk_business_counts"
        ),
        migrations.RunSQL(
            "ALTER TABLE businessmetrics ADD CONSTRAINT chk_business_request_breakdown CHECK (total_requests >= (approved_requests + rejected_requests))",
            reverse_sql="ALTER TABLE businessmetrics DROP CONSTRAINT chk_business_request_breakdown"
        ),
        migrations.RunSQL(
            "ALTER TABLE businessmetrics ADD CONSTRAINT chk_business_uptime CHECK (system_uptime_percent >= 0 AND system_uptime_percent <= 100)",
            reverse_sql="ALTER TABLE businessmetrics DROP CONSTRAINT chk_business_uptime"
        ),
        
        # Rate limiting constraints
        migrations.RunSQL(
            "ALTER TABLE otpratelimit ADD CONSTRAINT chk_rate_limit_window CHECK (window_end > window_start)",
            reverse_sql="ALTER TABLE otpratelimit DROP CONSTRAINT chk_rate_limit_window"
        ),
        migrations.RunSQL(
            "ALTER TABLE otpratelimit ADD CONSTRAINT chk_rate_limit_attempts CHECK (attempt_count >= 0)",
            reverse_sql="ALTER TABLE otpratelimit DROP CONSTRAINT chk_rate_limit_attempts"
        ),
    ]