# Generated by Django 4.2.7 on 2024-01-15 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_oracle_constraints'),
    ]

    operations = [
        # Create sequences for reference number generation
        migrations.RunSQL(
            """
            CREATE SEQUENCE customer_ref_seq
            START WITH 100000
            INCREMENT BY 1
            NOCACHE
            NOCYCLE
            """,
            reverse_sql="DROP SEQUENCE customer_ref_seq"
        ),
        
        migrations.RunSQL(
            """
            CREATE SEQUENCE limit_request_ref_seq
            START WITH 1000000
            INCREMENT BY 1
            NOCACHE
            NOCYCLE
            """,
            reverse_sql="DROP SEQUENCE limit_request_ref_seq"
        ),
        
        migrations.RunSQL(
            """
            CREATE SEQUENCE notification_ref_seq
            START WITH 10000000
            INCREMENT BY 1
            NOCACHE
            NOCYCLE
            """,
            reverse_sql="DROP SEQUENCE notification_ref_seq"
        ),
        
        migrations.RunSQL(
            """
            CREATE SEQUENCE otp_session_seq
            START WITH 1000000000
            INCREMENT BY 1
            NOCACHE
            NOCYCLE
            """,
            reverse_sql="DROP SEQUENCE otp_session_seq"
        ),
        
        # Create triggers for automatic reference number generation
        migrations.RunSQL(
            """
            CREATE OR REPLACE TRIGGER trg_customer_ref_num
            BEFORE INSERT ON customer
            FOR EACH ROW
            WHEN (NEW.customer_reference IS NULL)
            BEGIN
                SELECT 'CUST' || LPAD(customer_ref_seq.NEXTVAL, 6, '0') INTO :NEW.customer_reference FROM DUAL;
            END;
            """,
            reverse_sql="DROP TRIGGER trg_customer_ref_num"
        ),
        
        migrations.RunSQL(
            """
            CREATE OR REPLACE TRIGGER trg_limit_request_ref_num
            BEFORE INSERT ON limitrequest
            FOR EACH ROW
            WHEN (NEW.reference_number IS NULL)
            BEGIN
                SELECT 'LR' || LPAD(limit_request_ref_seq.NEXTVAL, 8, '0') INTO :NEW.reference_number FROM DUAL;
            END;
            """,
            reverse_sql="DROP TRIGGER trg_limit_request_ref_num"
        ),
        
        migrations.RunSQL(
            """
            CREATE OR REPLACE TRIGGER trg_otp_session_id
            BEFORE INSERT ON otplog
            FOR EACH ROW
            WHEN (NEW.session_id IS NULL)
            BEGIN
                SELECT 'OTP' || LPAD(otp_session_seq.NEXTVAL, 10, '0') INTO :NEW.session_id FROM DUAL;
            END;
            """,
            reverse_sql="DROP TRIGGER trg_otp_session_id"
        ),
        
        # Create audit triggers for tracking changes
        migrations.RunSQL(
            """
            CREATE OR REPLACE TRIGGER trg_customer_audit
            BEFORE UPDATE ON customer
            FOR EACH ROW
            BEGIN
                :NEW.updated_at := SYSTIMESTAMP;
            END;
            """,
            reverse_sql="DROP TRIGGER trg_customer_audit"
        ),
        
        migrations.RunSQL(
            """
            CREATE OR REPLACE TRIGGER trg_limitrequest_audit
            BEFORE UPDATE ON limitrequest
            FOR EACH ROW
            BEGIN
                :NEW.updated_at := SYSTIMESTAMP;
                
                -- Calculate processing time when status changes to completed states
                IF :NEW.status IN ('approved', 'rejected', 'implemented') 
                   AND :OLD.status NOT IN ('approved', 'rejected', 'implemented') THEN
                    :NEW.processing_time_hours := 
                        ROUND((SYSTIMESTAMP - :NEW.created_at) * 24, 2);
                END IF;
                
                -- Set review timestamp
                IF :NEW.status IN ('approved', 'rejected') 
                   AND :OLD.status NOT IN ('approved', 'rejected') THEN
                    :NEW.reviewed_at := SYSTIMESTAMP;
                END IF;
                
                -- Set implementation timestamp
                IF :NEW.status = 'implemented' 
                   AND :OLD.status != 'implemented' THEN
                    :NEW.implemented_at := SYSTIMESTAMP;
                END IF;
            END;
            """,
            reverse_sql="DROP TRIGGER trg_limitrequest_audit"
        ),
        
        migrations.RunSQL(
            """
            CREATE OR REPLACE TRIGGER trg_carddetail_limit_sync
            AFTER UPDATE OF current_limit ON carddetail
            FOR EACH ROW
            WHEN (NEW.current_limit != OLD.current_limit)
            BEGIN
                -- Update customer analytics when card limit changes
                UPDATE customeranalytics 
                SET total_limit_increase = total_limit_increase + (:NEW.current_limit - :OLD.current_limit),
                    updated_at = SYSTIMESTAMP
                WHERE customer_id = :NEW.customer_id;
            END;
            """,
            reverse_sql="DROP TRIGGER trg_carddetail_limit_sync"
        ),
        
        # Create automatic cleanup triggers
        migrations.RunSQL(
            """
            CREATE OR REPLACE TRIGGER trg_otp_expire_cleanup
            BEFORE INSERT ON otplog
            FOR EACH ROW
            BEGIN
                -- Clean up expired OTPs before inserting new ones
                DELETE FROM otplog 
                WHERE expires_at < SYSTIMESTAMP 
                AND status = 'GENERATED'
                AND phone_number = :NEW.phone_number;
            END;
            """,
            reverse_sql="DROP TRIGGER trg_otp_expire_cleanup"
        ),
        
        # Create performance optimization triggers
        migrations.RunSQL(
            """
            CREATE OR REPLACE TRIGGER trg_analytics_update
            AFTER INSERT OR UPDATE ON limitrequest
            FOR EACH ROW
            BEGIN
                -- Update customer analytics in real-time
                MERGE INTO customeranalytics ca
                USING (SELECT :NEW.customer_id as customer_id FROM DUAL) src
                ON (ca.customer_id = src.customer_id)
                WHEN MATCHED THEN
                    UPDATE SET 
                        total_requests = (
                            SELECT COUNT(*) FROM limitrequest 
                            WHERE customer_id = :NEW.customer_id
                        ),
                        approved_requests = (
                            SELECT COUNT(*) FROM limitrequest 
                            WHERE customer_id = :NEW.customer_id AND status = 'approved'
                        ),
                        rejected_requests = (
                            SELECT COUNT(*) FROM limitrequest 
                            WHERE customer_id = :NEW.customer_id AND status = 'rejected'
                        ),
                        last_request_date = :NEW.created_at,
                        updated_at = SYSTIMESTAMP
                WHEN NOT MATCHED THEN
                    INSERT (id, customer_id, total_requests, approved_requests, rejected_requests, 
                           last_request_date, created_at, updated_at)
                    VALUES (SYS_GUID(), :NEW.customer_id, 1, 
                           CASE WHEN :NEW.status = 'approved' THEN 1 ELSE 0 END,
                           CASE WHEN :NEW.status = 'rejected' THEN 1 ELSE 0 END,
                           :NEW.created_at, SYSTIMESTAMP, SYSTIMESTAMP);
            END;
            """,
            reverse_sql="DROP TRIGGER trg_analytics_update"
        ),
        
        # Create partitioning for large tables (Oracle 12c+)
        migrations.RunSQL(
            """
            -- Partition notification log by month for performance
            ALTER TABLE notificationlog MODIFY
            PARTITION BY RANGE (created_at) INTERVAL (INTERVAL '1' MONTH)
            (
                PARTITION p_notifications_initial VALUES LESS THAN (DATE '2024-02-01')
            )
            """,
            reverse_sql="-- Partitioning cannot be easily reversed"
        ),
        
        migrations.RunSQL(
            """
            -- Partition OTP audit log by month
            ALTER TABLE otpauditlog MODIFY  
            PARTITION BY RANGE (timestamp) INTERVAL (INTERVAL '1' MONTH)
            (
                PARTITION p_otp_audit_initial VALUES LESS THAN (DATE '2024-02-01')
            )
            """,
            reverse_sql="-- Partitioning cannot be easily reversed"
        ),
        
        migrations.RunSQL(
            """
            -- Partition analytics metrics by date
            ALTER TABLE analyticsmetric MODIFY
            PARTITION BY RANGE (date_partition) INTERVAL (INTERVAL '1' MONTH)
            (
                PARTITION p_analytics_initial VALUES LESS THAN (DATE '2024-02-01')
            )
            """,
            reverse_sql="-- Partitioning cannot be easily reversed"
        ),
        
        # Create materialized views for reporting
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW mv_daily_business_summary
            BUILD IMMEDIATE
            REFRESH FAST ON DEMAND
            AS
            SELECT 
                TRUNC(lr.created_at) as business_date,
                COUNT(*) as total_requests,
                SUM(CASE WHEN lr.status = 'approved' THEN 1 ELSE 0 END) as approved_requests,
                SUM(CASE WHEN lr.status = 'rejected' THEN 1 ELSE 0 END) as rejected_requests,
                SUM(CASE WHEN lr.auto_approved = 1 THEN 1 ELSE 0 END) as auto_approved_requests,
                AVG(lr.processing_time_hours) as avg_processing_time,
                SUM(CASE WHEN lr.status = 'approved' THEN lr.approved_limit - lr.current_limit ELSE 0 END) as total_limit_increase,
                COUNT(DISTINCT lr.customer_id) as unique_customers
            FROM limitrequest lr
            WHERE lr.created_at >= TRUNC(SYSDATE) - 365  -- Last year
            GROUP BY TRUNC(lr.created_at)
            """,
            reverse_sql="DROP MATERIALIZED VIEW mv_daily_business_summary"
        ),
        
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW mv_customer_risk_profile
            BUILD IMMEDIATE  
            REFRESH FAST ON DEMAND
            AS
            SELECT 
                c.id as customer_id,
                c.firebase_uid,
                ca.total_requests,
                ca.approved_requests,
                ca.rejected_requests,
                ca.risk_score,
                CASE 
                    WHEN ca.rejected_requests = 0 THEN 'LOW'
                    WHEN ca.rejected_requests / NULLIF(ca.total_requests, 0) < 0.2 THEN 'LOW'
                    WHEN ca.rejected_requests / NULLIF(ca.total_requests, 0) < 0.5 THEN 'MEDIUM'
                    ELSE 'HIGH'
                END as risk_category,
                c.created_at as customer_since,
                ca.last_request_date
            FROM customer c
            LEFT JOIN customeranalytics ca ON c.id = ca.customer_id
            WHERE c.is_active = 1
            """,
            reverse_sql="DROP MATERIALIZED VIEW mv_customer_risk_profile"
        ),
    ]