"""
Django settings for card_limit_system project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-change-this-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_filters',
    'drf_spectacular',
]

LOCAL_APPS = [
    'apps.authentication',
    'apps.customers', 
    'apps.requests',
    'apps.notifications',
    'apps.otp',
    'core',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.FirebaseAuthenticationMiddleware',
    'core.middleware.RateLimitMiddleware',
    'core.middleware.AuditLogMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'card_limit_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'card_limit_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Database Configuration - SQLite for development, Oracle for production
if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # Oracle Database Configuration for production
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.oracle',
            'NAME': config('DB_NAME', default='XEPDB1'),
            'USER': config('DB_USER', default='card_limit_user'),
            'PASSWORD': config('DB_PASSWORD', default='secure_password'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='1521'),
            'OPTIONS': {
                'threaded': True,
            },
        }
    }

# Oracle Connection Pool Configuration
ORACLE_CONFIG = {
    'user': config('ORACLE_USER', default='card_limit_user'),
    'password': config('ORACLE_PASSWORD', default='secure_password'),
    'dsn': config('ORACLE_DSN', default='localhost:1521/XEPDB1'),
    'min_connections': config('ORACLE_MIN_CONNECTIONS', default=2, cast=int),
    'max_connections': config('ORACLE_MAX_CONNECTIONS', default=10, cast=int),
    'increment': config('ORACLE_INCREMENT', default=1, cast=int),
    'encoding': 'UTF-8',
    'nencoding': 'UTF-8',
    'threaded': True
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = config('TIME_ZONE', default='Asia/Kolkata')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.authentication.FirebaseAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',
}

# API Documentation Configuration
SPECTACULAR_SETTINGS = {
    'TITLE': 'HDFC Card Limit Increase System API',
    'DESCRIPTION': 'Comprehensive REST API for HDFC Bank card and netbanking limit increase requests',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
    },
    'AUTHENTICATION_WHITELIST': [
        'core.authentication.FirebaseAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
}


# CORS Configuration
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://127.0.0.1:3000',
    cast=lambda v: [s.strip() for s in v.split(',')]
)

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'firebase-token',
]


# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# CSRF Settings
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)


# Firebase Configuration
FIREBASE_CONFIG = {
    'type': 'service_account',
    'project_id': config('FIREBASE_PROJECT_ID', default='hdfc-card-limit-system'),
    'private_key_id': config('FIREBASE_PRIVATE_KEY_ID', default=''),
    'private_key': config('FIREBASE_PRIVATE_KEY', default='').replace('\\n', '\n'),
    'client_email': config('FIREBASE_CLIENT_EMAIL', default=''),
    'client_id': config('FIREBASE_CLIENT_ID', default=''),
    'auth_uri': 'https://accounts.google.com/o/oauth2/auth',
    'token_uri': 'https://oauth2.googleapis.com/token',
    'auth_provider_x509_cert_url': 'https://www.googleapis.com/oauth2/v1/certs',
    'client_x509_cert_url': config('FIREBASE_CLIENT_CERT_URL', default=''),
}

# Firebase Database URL
FIREBASE_DATABASE_URL = config('FIREBASE_DATABASE_URL', default='')


# Twilio Configuration
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default='')
TWILIO_PHONE_NUMBER = config('TWILIO_PHONE_NUMBER', default='')
TWILIO_WHATSAPP_NUMBER = config('TWILIO_WHATSAPP_NUMBER', default='whatsapp:+14155238886')
TWILIO_VERIFY_SERVICE_SID = config('TWILIO_VERIFY_SERVICE_SID', default='')


# SendGrid Configuration
SENDGRID_API_KEY = config('SENDGRID_API_KEY', default='')
SENDGRID_FROM_EMAIL = config('SENDGRID_FROM_EMAIL', default='noreply@hdfc.com')
SENDGRID_FROM_NAME = config('SENDGRID_FROM_NAME', default='HDFC Bank')


# OneSignal Configuration
ONESIGNAL_APP_ID = config('ONESIGNAL_APP_ID', default='')
ONESIGNAL_REST_API_KEY = config('ONESIGNAL_REST_API_KEY', default='')
ONESIGNAL_USER_AUTH_KEY = config('ONESIGNAL_USER_AUTH_KEY', default='')


# Cache Configuration - Dummy cache for development, Redis for production
if DEBUG:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        }
    }
else:
    # Redis Configuration for production
    REDIS_URL = config('REDIS_URL', default='redis://localhost:6379/0')
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        }
    }


# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'security.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'card_limit_system': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'security': {
            'handlers': ['security_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'core.firebase_service': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'core.twilio_service': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'core.sendgrid_service': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'core.onesignal_service': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'core.oracle_service': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}


# Email Configuration (Fallback to Django's email backend)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@hdfc.com')


# Rate Limiting Configuration
RATE_LIMIT_SETTINGS = {
    'login_attempts': {
        'limit': 5,
        'window': 900,  # 15 minutes
        'block_duration': 1800,  # 30 minutes
    },
    'otp_requests': {
        'limit': 3,
        'window': 300,  # 5 minutes
        'block_duration': 900,  # 15 minutes
    },
    'api_requests': {
        'limit': 100,
        'window': 3600,  # 1 hour
        'block_duration': 3600,  # 1 hour
    },
    'limit_requests': {
        'limit': 5,
        'window': 86400,  # 24 hours
        'block_duration': 86400,  # 24 hours
    },
}


# Encryption Configuration
ENCRYPTION_KEY = config('ENCRYPTION_KEY', default='').encode()
if not ENCRYPTION_KEY:
    # Generate a default key for development (DO NOT use in production)
    from cryptography.fernet import Fernet
    ENCRYPTION_KEY = Fernet.generate_key()


# Business Rules Configuration
BUSINESS_RULES = {
    'card_limits': {
        'min_credit_limit': 10000,
        'max_credit_limit': 10000000,
        'min_increase_amount': 5000,
        'max_increase_percentage': 500,  # 500% of current limit
    },
    'netbanking_limits': {
        'min_daily_limit': 1000,
        'max_daily_limit': 10000000,
        'min_per_transaction_limit': 100,
        'max_per_transaction_limit': 5000000,
    },
    'approval_workflow': {
        'auto_approve_threshold': 50000,
        'manager_approval_threshold': 500000,
        'senior_manager_approval_threshold': 2000000,
    },
    'risk_assessment': {
        'min_account_age_days': 90,
        'min_credit_score': 650,
        'max_utilization_ratio': 0.8,
        'min_income': 300000,
    },
}


# Notification Templates
NOTIFICATION_TEMPLATES = {
    'sms': {
        'otp': 'Your HDFC verification code is {otp}. Valid for 5 minutes. Do not share this code.',
        'request_submitted': 'Your limit increase request #{request_id} has been submitted and is under review.',
        'request_approved': 'Congratulations! Your limit increase request #{request_id} has been approved.',
        'request_rejected': 'Your limit increase request #{request_id} has been declined. Please contact customer care.',
    },
    'email': {
        'welcome': 'Welcome to HDFC Card Limit System',
        'request_confirmation': 'Limit Increase Request Confirmation',
        'approval_notification': 'Limit Increase Request Approved',
        'rejection_notification': 'Limit Increase Request Update',
    },
    'push': {
        'request_status': 'Limit increase request update',
        'new_feature': 'New feature available',
        'security_alert': 'Security notification',
    },
}


# Performance Monitoring
PERFORMANCE_MONITORING = {
    'slow_query_threshold': 1.0,  # seconds
    'memory_usage_alert_threshold': 0.8,  # 80%
    'cpu_usage_alert_threshold': 0.8,  # 80%
    'disk_usage_alert_threshold': 0.9,  # 90%
}


# Development/Testing specific settings
if DEBUG:
    # Allow all hosts in development
    ALLOWED_HOSTS = ['*']
    
    # Disable password validation in development
    AUTH_PASSWORD_VALIDATORS = []
    
    # Use console email backend in development
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    
    # Add debug toolbar if available
    try:
        import debug_toolbar
        INSTALLED_APPS.append('debug_toolbar')
        MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')
        INTERNAL_IPS = ['127.0.0.1', '::1']
    except ImportError:
        pass


# Production specific settings
if not DEBUG:
    # Security settings for production
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    
    # Logging to files in production
    LOGGING['handlers']['file']['filename'] = '/var/log/django/django.log'
    LOGGING['handlers']['security_file']['filename'] = '/var/log/django/security.log'