# Generated by Django 4.2.7 on 2024-01-15 10:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique customer identifier', primary_key=True, serialize=False)),
                ('firebase_uid', models.CharField(db_index=True, help_text='Firebase authentication user ID for linking', max_length=128, unique=True)),
                ('name', models.CharField(help_text='Customer full name', max_length=100)),
                ('date_of_birth', models.DateField(help_text='Customer date of birth for verification')),
                ('email', models.CharField(db_index=True, help_text='Email address (encrypted)', max_length=255, unique=True)),
                ('phone', models.CharField(db_index=True, help_text='Phone number (encrypted, +91xxxxxxxxxx format)', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Account status flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Account creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last profile update timestamp')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customer',
                'indexes': [
                    models.Index(fields=['firebase_uid'], name='customer_firebase_uid_idx'),
                    models.Index(fields=['email'], name='customer_email_idx'),
                    models.Index(fields=['phone'], name='customer_phone_idx'),
                    models.Index(fields=['is_active', 'created_at'], name='customer_is_active_created_at_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='CardDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique card detail identifier', primary_key=True, serialize=False)),
                ('card_type', models.CharField(choices=[('credit', 'Credit Card'), ('debit', 'Debit Card')], help_text='Type of card (credit/debit)', max_length=10)),
                ('last4', models.CharField(help_text='Last 4 digits of card number (encrypted)', max_length=255)),
                ('expiry_month', models.PositiveSmallIntegerField(help_text='Card expiry month (1-12)')),
                ('expiry_year', models.PositiveSmallIntegerField(help_text='Card expiry year')),
                ('token_id', models.CharField(blank=True, help_text='Tokenized card reference from bank system (encrypted)', max_length=255, null=True)),
                ('current_limit', models.DecimalField(decimal_places=2, default=0.0, help_text='Current transaction limit in INR', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Card status flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('customer', models.ForeignKey(help_text='Reference to Customer', on_delete=django.db.models.deletion.CASCADE, related_name='card_details', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Card Detail',
                'verbose_name_plural': 'Card Details',
                'db_table': 'carddetail',
                'indexes': [
                    models.Index(fields=['customer', 'is_active'], name='carddetail_customer_is_active_idx'),
                    models.Index(fields=['card_type'], name='carddetail_card_type_idx'),
                    models.Index(fields=['customer', 'card_type', 'is_active'], name='carddetail_customer_card_type_is_active_idx'),
                ],
                'unique_together': {('customer', 'last4', 'expiry_month', 'expiry_year')},
            },
        ),
    ]