# Generated by Django 4.2.7 on 2024-01-15 10:35

from django.db import migrations, models
import django.db.models.deletion
import uuid
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique request identifier', primary_key=True, serialize=False)),
                ('reference_number', models.CharField(db_index=True, help_text='Unique reference number for tracking', max_length=50, unique=True)),
                ('request_type', models.CharField(choices=[('credit_limit', 'Credit Card Limit'), ('debit_limit', 'Debit Card Limit'), ('netbanking_limit', 'Net Banking Limit')], help_text='Type of limit increase request', max_length=20)),
                ('current_limit', models.DecimalField(decimal_places=2, help_text='Current limit amount in INR', max_digits=12)),
                ('requested_limit', models.DecimalField(decimal_places=2, help_text='Requested limit amount in INR', max_digits=12)),
                ('approved_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Final approved limit amount in INR', max_digits=12, null=True)),
                ('reason', models.TextField(help_text='Reason for limit increase request')),
                ('supporting_documents', models.JSONField(blank=True, default=list, help_text='List of uploaded document references')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('implemented', 'Implemented'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the request', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', help_text='Request priority level', max_length=10)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated risk score (0-100)', max_digits=5, null=True)),
                ('auto_approved', models.BooleanField(default=False, help_text='Whether request was auto-approved')),
                ('reviewer_notes', models.TextField(blank=True, help_text='Internal reviewer notes')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable')),
                ('processing_time_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Total processing time in hours', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Request creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Review completion timestamp', null=True)),
                ('implemented_at', models.DateTimeField(blank=True, help_text='Implementation timestamp', null=True)),
                ('customer', models.ForeignKey(help_text='Customer making the request', on_delete=django.db.models.deletion.CASCADE, related_name='limit_requests', to='customers.customer')),
                ('card_detail', models.ForeignKey(blank=True, help_text='Related card for card limit requests', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limit_requests', to='customers.carddetail')),
            ],
            options={
                'verbose_name': 'Limit Request',
                'verbose_name_plural': 'Limit Requests',
                'db_table': 'limitrequest',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['customer', 'status'], name='limitrequest_customer_status_idx'),
                    models.Index(fields=['reference_number'], name='limitrequest_reference_number_idx'),
                    models.Index(fields=['status', 'priority'], name='limitrequest_status_priority_idx'),
                    models.Index(fields=['created_at'], name='limitrequest_created_at_idx'),
                    models.Index(fields=['request_type', 'status'], name='limitrequest_request_type_status_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='RequestDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique document identifier', primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('income_proof', 'Income Proof'), ('bank_statement', 'Bank Statement'), ('identity_proof', 'Identity Proof'), ('address_proof', 'Address Proof'), ('form16', 'Form 16'), ('salary_slip', 'Salary Slip'), ('other', 'Other Document')], help_text='Type of document uploaded', max_length=20)),
                ('file_name', models.CharField(help_text='Original filename', max_length=255)),
                ('file_path', models.CharField(help_text='Encrypted file storage path', max_length=500)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(help_text='MIME type of the file', max_length=100)),
                ('checksum', models.CharField(help_text='File integrity checksum', max_length=128)),
                ('is_verified', models.BooleanField(default=False, help_text='Document verification status')),
                ('verification_notes', models.TextField(blank=True, help_text='Document verification notes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Upload timestamp')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Verification timestamp', null=True)),
                ('limit_request', models.ForeignKey(help_text='Related limit request', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='requests.limitrequest')),
            ],
            options={
                'verbose_name': 'Request Document',
                'verbose_name_plural': 'Request Documents',
                'db_table': 'requestdocument',
                'ordering': ['-uploaded_at'],
                'indexes': [
                    models.Index(fields=['limit_request', 'document_type'], name='requestdocument_limit_request_document_type_idx'),
                    models.Index(fields=['is_verified'], name='requestdocument_is_verified_idx'),
                    models.Index(fields=['uploaded_at'], name='requestdocument_uploaded_at_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique workflow identifier', primary_key=True, serialize=False)),
                ('step_name', models.CharField(help_text='Name of the workflow step', max_length=100)),
                ('step_order', models.PositiveSmallIntegerField(help_text='Order of this step in the workflow')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', help_text='Status of this workflow step', max_length=20)),
                ('assignee_role', models.CharField(blank=True, help_text='Role responsible for this step', max_length=50)),
                ('assignee_user', models.CharField(blank=True, help_text='Specific user assigned to this step', max_length=100)),
                ('started_at', models.DateTimeField(blank=True, help_text='Step start timestamp', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Step completion timestamp', null=True)),
                ('notes', models.TextField(blank=True, help_text='Step execution notes')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Time taken for this step in minutes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Workflow step creation timestamp')),
                ('limit_request', models.ForeignKey(help_text='Related limit request', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='requests.limitrequest')),
            ],
            options={
                'verbose_name': 'Approval Workflow',
                'verbose_name_plural': 'Approval Workflows',
                'db_table': 'approvalworkflow',
                'ordering': ['step_order'],
                'unique_together': {('limit_request', 'step_order')},
                'indexes': [
                    models.Index(fields=['limit_request', 'step_order'], name='approvalworkflow_limit_request_step_order_idx'),
                    models.Index(fields=['status'], name='approvalworkflow_status_idx'),
                    models.Index(fields=['assignee_role', 'status'], name='approvalworkflow_assignee_role_status_idx'),
                ],
            },
        ),
    ]