# Generated by Django 4.2.7 on 2024-01-15 10:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial_customers'),
        ('requests', '0002_initial_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique notification identifier', primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('PUSH', 'Push Notification'), ('SMS', 'SMS Message'), ('EMAIL', 'Email'), ('IN_APP', 'In-App Notification'), ('WHATSAPP', 'WhatsApp Message')], help_text='Type of notification sent', max_length=20)),
                ('category', models.CharField(choices=[('SECURITY', 'Security Alert'), ('TRANSACTION', 'Transaction Update'), ('MARKETING', 'Marketing Communication'), ('SERVICE', 'Service Notification'), ('LIMIT_REQUEST', 'Limit Request Update'), ('SYSTEM', 'System Notification'), ('REMINDER', 'Reminder')], help_text='Category of notification', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NORMAL', help_text='Priority level of notification', max_length=10)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued for Sending'), ('SENDING', 'Being Sent'), ('SENT', 'Successfully Sent'), ('DELIVERED', 'Delivered to Device'), ('READ', 'Read by User'), ('FAILED', 'Failed to Send'), ('EXPIRED', 'Expired Before Sending')], default='QUEUED', help_text='Current delivery status', max_length=20)),
                ('title', models.CharField(help_text='Notification title/subject', max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('recipient_info', models.JSONField(help_text='Recipient contact information (encrypted if needed)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional notification metadata')),
                ('template_id', models.CharField(blank=True, help_text='Template used for this notification', max_length=100)),
                ('external_id', models.CharField(blank=True, help_text='External service message ID', max_length=200)),
                ('delivery_attempts', models.PositiveSmallIntegerField(default=0, help_text='Number of delivery attempts')),
                ('last_attempt_at', models.DateTimeField(blank=True, help_text='Last delivery attempt timestamp', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Successful delivery timestamp', null=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='User read timestamp', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Notification expiration time', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if delivery failed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Notification creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last status update timestamp')),
                ('customer', models.ForeignKey(blank=True, help_text='Target customer (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='customers.customer')),
                ('related_request', models.ForeignKey(blank=True, help_text='Related limit request (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='requests.limitrequest')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'db_table': 'notificationlog',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['customer', 'notification_type'], name='notificationlog_customer_notification_type_idx'),
                    models.Index(fields=['status', 'created_at'], name='notificationlog_status_created_at_idx'),
                    models.Index(fields=['category', 'created_at'], name='notificationlog_category_created_at_idx'),
                    models.Index(fields=['priority', 'status'], name='notificationlog_priority_status_idx'),
                    models.Index(fields=['expires_at'], name='notificationlog_expires_at_idx'),
                    models.Index(fields=['external_id'], name='notificationlog_external_id_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique template identifier', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name for identification', max_length=100, unique=True)),
                ('notification_type', models.CharField(choices=[('PUSH', 'Push Notification'), ('SMS', 'SMS Message'), ('EMAIL', 'Email'), ('IN_APP', 'In-App Notification'), ('WHATSAPP', 'WhatsApp Message')], help_text='Type of notification this template is for', max_length=20)),
                ('category', models.CharField(choices=[('SECURITY', 'Security Alert'), ('TRANSACTION', 'Transaction Update'), ('MARKETING', 'Marketing Communication'), ('SERVICE', 'Service Notification'), ('LIMIT_REQUEST', 'Limit Request Update'), ('SYSTEM', 'System Notification'), ('REMINDER', 'Reminder')], help_text='Category of notification', max_length=20)),
                ('language', models.CharField(default='EN', help_text='Language code for the template', max_length=5)),
                ('title_template', models.CharField(help_text='Template for notification title with placeholders', max_length=200)),
                ('message_template', models.TextField(help_text='Template for notification message with placeholders')),
                ('variables', models.JSONField(default=list, help_text='List of available template variables')),
                ('is_active', models.BooleanField(default=True, help_text='Whether template is active')),
                ('version', models.PositiveSmallIntegerField(default=1, help_text='Template version number')),
                ('created_by', models.CharField(help_text='User who created the template', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Template creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last template update timestamp')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'db_table': 'notificationtemplate',
                'ordering': ['name'],
                'unique_together': {('name', 'language', 'version')},
                'indexes': [
                    models.Index(fields=['notification_type', 'category'], name='notificationtemplate_notification_type_category_idx'),
                    models.Index(fields=['is_active'], name='notificationtemplate_is_active_idx'),
                    models.Index(fields=['language'], name='notificationtemplate_language_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique preference identifier', primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('PUSH', 'Push Notification'), ('SMS', 'SMS Message'), ('EMAIL', 'Email'), ('IN_APP', 'In-App Notification'), ('WHATSAPP', 'WhatsApp Message')], help_text='Type of notification', max_length=20)),
                ('category', models.CharField(choices=[('SECURITY', 'Security Alert'), ('TRANSACTION', 'Transaction Update'), ('MARKETING', 'Marketing Communication'), ('SERVICE', 'Service Notification'), ('LIMIT_REQUEST', 'Limit Request Update'), ('SYSTEM', 'System Notification'), ('REMINDER', 'Reminder')], help_text='Category of notification', max_length=20)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether customer wants to receive this type of notification')),
                ('frequency', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('DAILY_DIGEST', 'Daily Digest'), ('WEEKLY_DIGEST', 'Weekly Digest'), ('DISABLED', 'Disabled')], default='IMMEDIATE', help_text='Notification frequency preference', max_length=20)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start of quiet hours (no notifications)', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End of quiet hours', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Preference creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last preference update timestamp')),
                ('customer', models.ForeignKey(help_text='Customer with these preferences', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notificationpreference',
                'unique_together': {('customer', 'notification_type', 'category')},
                'indexes': [
                    models.Index(fields=['customer', 'notification_type'], name='notificationpreference_customer_notification_type_idx'),
                    models.Index(fields=['is_enabled'], name='notificationpreference_is_enabled_idx'),
                ],
            },
        ),
    ]