# Generated by Django 4.2.7 on 2024-01-15 10:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial_customers'),
        ('notifications', '0003_initial_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique OTP log identifier', primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text='Unique session identifier for OTP verification', max_length=128, unique=True)),
                ('otp_type', models.CharField(choices=[('LOGIN', 'Login Verification'), ('TRANSACTION', 'Transaction Verification'), ('PROFILE_UPDATE', 'Profile Update'), ('LIMIT_REQUEST', 'Limit Request'), ('PASSWORD_RESET', 'Password Reset')], help_text='Purpose of OTP verification', max_length=20)),
                ('phone_number', models.CharField(help_text='Phone number for OTP delivery (encrypted)', max_length=255)),
                ('email', models.CharField(blank=True, help_text='Email address for OTP delivery (encrypted)', max_length=255)),
                ('otp_hash', models.CharField(help_text='Hashed OTP value (never store plaintext)', max_length=128)),
                ('delivery_method', models.CharField(choices=[('SMS', 'SMS to Phone'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('VOICE', 'Voice Call')], help_text='Method used to deliver OTP', max_length=20)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('SENT', 'Sent Successfully'), ('SEND_FAILED', 'Send Failed'), ('VERIFIED', 'Successfully Verified'), ('EXPIRED', 'Expired'), ('FAILED_ATTEMPT', 'Failed Verification'), ('BLOCKED', 'Blocked due to max attempts')], default='GENERATED', help_text='Current status of OTP', max_length=20)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0, help_text='Number of verification attempts')),
                ('max_attempts', models.PositiveSmallIntegerField(default=3, help_text='Maximum allowed verification attempts')),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='OTP generation timestamp')),
                ('sent_at', models.DateTimeField(blank=True, help_text='OTP sending timestamp', null=True)),
                ('expires_at', models.DateTimeField(help_text='OTP expiration timestamp')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Successful verification timestamp', null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, help_text='Last verification attempt timestamp', null=True)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the request')),
                ('user_agent', models.TextField(help_text='User agent string of the request')),
                ('external_reference', models.CharField(blank=True, help_text='External service reference (e.g., Twilio SID)', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional OTP metadata')),
                ('customer', models.ForeignKey(blank=True, help_text='Associated customer (if logged in)', null=True, on_delete=models.deletion.CASCADE, related_name='otp_logs', to='customers.customer')),
            ],
            options={
                'verbose_name': 'OTP Log',
                'verbose_name_plural': 'OTP Logs',
                'db_table': 'otplog',
                'ordering': ['-generated_at'],
                'indexes': [
                    models.Index(fields=['session_id'], name='otplog_session_id_idx'),
                    models.Index(fields=['phone_number', 'status'], name='otplog_phone_number_status_idx'),
                    models.Index(fields=['generated_at', 'otp_type'], name='otplog_generated_at_otp_type_idx'),
                    models.Index(fields=['expires_at', 'status'], name='otplog_expires_at_status_idx'),
                    models.Index(fields=['ip_address'], name='otplog_ip_address_idx'),
                    models.Index(fields=['customer', 'otp_type'], name='otplog_customer_otp_type_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='OTPRateLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique rate limit identifier', primary_key=True, serialize=False)),
                ('identifier', models.CharField(help_text='Rate limit identifier (phone/email/IP)', max_length=255)),
                ('identifier_type', models.CharField(choices=[('PHONE', 'Phone Number'), ('EMAIL', 'Email Address'), ('IP', 'IP Address'), ('CUSTOMER', 'Customer ID')], help_text='Type of identifier being rate limited', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0, help_text='Current attempt count in time window')),
                ('window_start', models.DateTimeField(help_text='Start of current rate limit window')),
                ('window_end', models.DateTimeField(help_text='End of current rate limit window')),
                ('is_blocked', models.BooleanField(default=False, help_text='Whether identifier is currently blocked')),
                ('block_until', models.DateTimeField(blank=True, help_text='Block expiration timestamp', null=True)),
                ('last_attempt_at', models.DateTimeField(help_text='Last OTP request timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Rate limit record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last rate limit update timestamp')),
            ],
            options={
                'verbose_name': 'OTP Rate Limit',
                'verbose_name_plural': 'OTP Rate Limits',
                'db_table': 'otpratelimit',
                'unique_together': {('identifier', 'identifier_type')},
                'indexes': [
                    models.Index(fields=['identifier', 'identifier_type'], name='otpratelimit_identifier_identifier_type_idx'),
                    models.Index(fields=['is_blocked', 'block_until'], name='otpratelimit_is_blocked_block_until_idx'),
                    models.Index(fields=['window_end'], name='otpratelimit_window_end_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='OTPAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique audit log identifier', primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('GENERATE', 'OTP Generated'), ('SEND', 'OTP Sent'), ('VERIFY', 'OTP Verification Attempt'), ('EXPIRE', 'OTP Expired'), ('BLOCK', 'User/IP Blocked'), ('UNBLOCK', 'User/IP Unblocked')], help_text='Action performed', max_length=20)),
                ('result', models.CharField(choices=[('SUCCESS', 'Successful'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked'), ('EXPIRED', 'Expired')], help_text='Result of the action', max_length=20)),
                ('identifier', models.CharField(help_text='Phone/email/IP involved in action', max_length=255)),
                ('session_id', models.CharField(blank=True, help_text='Related OTP session ID', max_length=128)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the request')),
                ('user_agent', models.TextField(help_text='User agent string')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional audit details')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Audit event timestamp')),
                ('customer', models.ForeignKey(blank=True, help_text='Associated customer (if applicable)', null=True, on_delete=models.deletion.CASCADE, related_name='otp_audit_logs', to='customers.customer')),
            ],
            options={
                'verbose_name': 'OTP Audit Log',
                'verbose_name_plural': 'OTP Audit Logs',
                'db_table': 'otpauditlog',
                'ordering': ['-timestamp'],
                'indexes': [
                    models.Index(fields=['action', 'timestamp'], name='otpauditlog_action_timestamp_idx'),
                    models.Index(fields=['identifier'], name='otpauditlog_identifier_idx'),
                    models.Index(fields=['ip_address', 'timestamp'], name='otpauditlog_ip_address_timestamp_idx'),
                    models.Index(fields=['session_id'], name='otpauditlog_session_id_idx'),
                    models.Index(fields=['customer', 'action'], name='otpauditlog_customer_action_idx'),
                ],
            },
        ),
    ]