# Generated by Django 4.2.7 on 2024-01-15 10:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial_customers'),
        ('requests', '0002_initial_requests'),
        ('notifications', '0003_initial_notifications'),
        ('otp', '0004_initial_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique metric identifier', primary_key=True, serialize=False)),
                ('metric_name', models.CharField(help_text='Name of the metric being tracked', max_length=100)),
                ('metric_type', models.CharField(choices=[('COUNTER', 'Counter'), ('GAUGE', 'Gauge'), ('HISTOGRAM', 'Histogram'), ('TIMER', 'Timer')], help_text='Type of metric', max_length=20)),
                ('category', models.CharField(choices=[('SYSTEM', 'System Performance'), ('BUSINESS', 'Business Metrics'), ('USER', 'User Behavior'), ('SECURITY', 'Security Metrics'), ('FINANCIAL', 'Financial Metrics')], help_text='Metric category', max_length=20)),
                ('value', models.DecimalField(decimal_places=4, help_text='Metric value', max_digits=20)),
                ('unit', models.CharField(help_text='Unit of measurement', max_length=50)),
                ('tags', models.JSONField(blank=True, default=dict, help_text='Additional metric tags/dimensions')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Metric recording timestamp')),
                ('date_partition', models.DateField(auto_now_add=True, help_text='Date partition for efficient querying')),
            ],
            options={
                'verbose_name': 'Analytics Metric',
                'verbose_name_plural': 'Analytics Metrics',
                'db_table': 'analyticsmetric',
                'ordering': ['-timestamp'],
                'indexes': [
                    models.Index(fields=['metric_name', 'timestamp'], name='analyticsmetric_metric_name_timestamp_idx'),
                    models.Index(fields=['category', 'date_partition'], name='analyticsmetric_category_date_partition_idx'),
                    models.Index(fields=['date_partition'], name='analyticsmetric_date_partition_idx'),
                    models.Index(fields=['metric_type', 'timestamp'], name='analyticsmetric_metric_type_timestamp_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='CustomerAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique analytics identifier', primary_key=True, serialize=False)),
                ('total_requests', models.PositiveIntegerField(default=0, help_text='Total limit requests by customer')),
                ('approved_requests', models.PositiveIntegerField(default=0, help_text='Number of approved requests')),
                ('rejected_requests', models.PositiveIntegerField(default=0, help_text='Number of rejected requests')),
                ('avg_processing_time_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Average request processing time in hours', max_digits=10, null=True)),
                ('total_limit_increase', models.DecimalField(decimal_places=2, default=0, help_text='Total limit increase amount', max_digits=15)),
                ('last_request_date', models.DateTimeField(blank=True, help_text='Date of last limit request', null=True)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, help_text='Customer risk score (0-100)', max_digits=5, null=True)),
                ('satisfaction_score', models.DecimalField(blank=True, decimal_places=2, help_text='Customer satisfaction score (1-5)', max_digits=3, null=True)),
                ('preferred_contact_method', models.CharField(blank=True, help_text='Customer preferred contact method', max_length=20)),
                ('app_usage_frequency', models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('RARELY', 'Rarely')], help_text='App usage frequency', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Analytics record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last analytics update timestamp')),
                ('customer', models.OneToOneField(help_text='Customer this analytics data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer Analytics',
                'verbose_name_plural': 'Customer Analytics',
                'db_table': 'customeranalytics',
                'indexes': [
                    models.Index(fields=['total_requests'], name='customeranalytics_total_requests_idx'),
                    models.Index(fields=['risk_score'], name='customeranalytics_risk_score_idx'),
                    models.Index(fields=['last_request_date'], name='customeranalytics_last_request_date_idx'),
                    models.Index(fields=['satisfaction_score'], name='customeranalytics_satisfaction_score_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='SystemHealthMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique health metric identifier', primary_key=True, serialize=False)),
                ('metric_timestamp', models.DateTimeField(auto_now_add=True, help_text='Metric collection timestamp')),
                ('api_response_time_ms', models.PositiveIntegerField(help_text='Average API response time in milliseconds')),
                ('database_response_time_ms', models.PositiveIntegerField(help_text='Average database response time in milliseconds')),
                ('error_rate_percent', models.DecimalField(decimal_places=2, help_text='Error rate percentage', max_digits=5)),
                ('active_sessions', models.PositiveIntegerField(help_text='Number of active user sessions')),
                ('memory_usage_percent', models.DecimalField(decimal_places=2, help_text='Memory usage percentage', max_digits=5)),
                ('cpu_usage_percent', models.DecimalField(decimal_places=2, help_text='CPU usage percentage', max_digits=5)),
                ('disk_usage_percent', models.DecimalField(decimal_places=2, help_text='Disk usage percentage', max_digits=5)),
                ('external_service_status', models.JSONField(default=dict, help_text='Status of external services')),
                ('throughput_requests_per_minute', models.PositiveIntegerField(help_text='Request throughput per minute')),
                ('cache_hit_rate_percent', models.DecimalField(decimal_places=2, help_text='Cache hit rate percentage', max_digits=5)),
                ('date_partition', models.DateField(auto_now_add=True, help_text='Date partition for efficient querying')),
            ],
            options={
                'verbose_name': 'System Health Metrics',
                'verbose_name_plural': 'System Health Metrics',
                'db_table': 'systemhealthmetrics',
                'ordering': ['-metric_timestamp'],
                'indexes': [
                    models.Index(fields=['date_partition'], name='systemhealthmetrics_date_partition_idx'),
                    models.Index(fields=['metric_timestamp'], name='systemhealthmetrics_metric_timestamp_idx'),
                    models.Index(fields=['error_rate_percent'], name='systemhealthmetrics_error_rate_percent_idx'),
                    models.Index(fields=['api_response_time_ms'], name='systemhealthmetrics_api_response_time_ms_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='BusinessMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique business metric identifier', primary_key=True, serialize=False)),
                ('metric_date', models.DateField(help_text='Date for which metrics are calculated')),
                ('total_customers', models.PositiveIntegerField(default=0, help_text='Total number of customers')),
                ('new_customers', models.PositiveIntegerField(default=0, help_text='New customers registered')),
                ('active_customers', models.PositiveIntegerField(default=0, help_text='Active customers (used app in last 30 days)')),
                ('total_requests', models.PositiveIntegerField(default=0, help_text='Total limit increase requests')),
                ('approved_requests', models.PositiveIntegerField(default=0, help_text='Approved requests')),
                ('rejected_requests', models.PositiveIntegerField(default=0, help_text='Rejected requests')),
                ('auto_approved_requests', models.PositiveIntegerField(default=0, help_text='Auto-approved requests')),
                ('avg_processing_time_hours', models.DecimalField(decimal_places=2, default=0, help_text='Average processing time in hours', max_digits=10)),
                ('total_limit_increase_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total limit increase amount in INR', max_digits=15)),
                ('avg_limit_increase_amount', models.DecimalField(decimal_places=2, default=0, help_text='Average limit increase amount in INR', max_digits=12)),
                ('customer_satisfaction_score', models.DecimalField(blank=True, decimal_places=2, help_text='Average customer satisfaction score', max_digits=3, null=True)),
                ('system_uptime_percent', models.DecimalField(decimal_places=2, default=100, help_text='System uptime percentage', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Metric calculation timestamp')),
            ],
            options={
                'verbose_name': 'Business Metrics',
                'verbose_name_plural': 'Business Metrics',
                'db_table': 'businessmetrics',
                'ordering': ['-metric_date'],
                'unique_together': {('metric_date',)},
                'indexes': [
                    models.Index(fields=['metric_date'], name='businessmetrics_metric_date_idx'),
                    models.Index(fields=['total_customers'], name='businessmetrics_total_customers_idx'),
                    models.Index(fields=['total_requests'], name='businessmetrics_total_requests_idx'),
                ],
            },
        ),
    ]